### ISSUE TITLE
Error on TF 2.7

### ISSUE THREAD

**Issue by gergo-szabo** [cpuimage/Ranger21#1]
I got an error on TF 2.7. Any idea what is wrong? (colab replicate it with current libraries)

inputs = Input((20,20,3))
outputs = Conv2D(filters=3, kernel_size=(3, 3))(inputs)

model = Model(inputs=inputs, outputs=outputs)
optimizer = Ranger21(learning_rate=1e-3, num_epochs=100, steps_per_epoch=100)

model.compile(loss='mse', optimizer=optimizer)

ValueError: Could not interpret optimizer identifier: <backend.ranger21.Ranger21 object at 0x7f233e7481f0>

**Comment by cpuimage** [comment]
@gergo-szabo 
try modify the code.

from
```
class Ranger21(optimizer_v2.OptimizerV2):
```
to 
```
import tensorflow as tf
class Ranger21(tf.keras.optimizers.Optimizer):
```

**Comment by gergo-szabo** [comment]
It works. Thanks!
